#!/bin/bash

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m" # no color
LINE="-----------------------------------------"

user=`whoami`
branch=`git rev-parse --abbrev-ref HEAD`
config=$1
initial_start=0

source .env

echo
echo $LINE
echo " Start jc://remote/$REMOTE_CURRENT_STAGE/"
echo $LINE

if [ $user != "root" ]; then
  echo
  echo "Please run as root!"
  echo
  exit 0
fi

# CHECK IF .env FILE EXIST OR CREATE ONE

if [ -e ".env" ]; then
    :
else
  echo
  echo "Configuration file '.env' does not exist yet."
  echo "Create a copy from the file 'sample.env' and adapt it to your needs.'"
  echo "Do you want to create and edit the this file now [y|n]?"
  while : ; do
    read -n 1 k <& 1
    if [[ $k = y ]] ; then
      cp sample.env .env && sed -i "s|^REMOTE_DIR=.*|REMOTE_DIR=\"$(pwd)\"|" .env
      nano .env
      initial_start=1
      break
    elif [[ $k = n ]] ; then
      echo
      exit 0
    else
      echo
      echo " -> Press 'y' to create a file or 'n' to exit now: "
    fi
  done
fi

source .env

# SHOW DOCKER-CONTAINER STATUS

if [[ $ZIGBEE2MQTT_START = "YES" ]]; then
  CONTAINERS=(
    $REMOTE_DOCKER_SERVER
    $REMOTE_DOCKER_CLIENT
    mqtt4zigbee
    zigbee2mqtt
  )
else
  CONTAINERS=(
    $REMOTE_DOCKER_SERVER
    $REMOTE_DOCKER_CLIENT
  )
fi


for CONTAINER in "${CONTAINERS[@]}"; do
  CID=$(docker ps --filter "name=^/${CONTAINER}$" --format "{{.ID}}")

  if [[ -n "$CID" ]]; then
    STARTED_AT_RAW=$(docker inspect -f '{{.State.StartedAt}}' "$CID")
    STARTED_TS=$(date -d "$STARTED_AT_RAW" +%s)
    STARTED_FMT=$(date -d "$STARTED_AT_RAW" "+%Y-%m-%d %H:%M:%S")

    echo -e " ${GREEN}Running${NC}: ${CONTAINER}  (id = ${CID}, started @ ${STARTED_FMT})"
  else
    echo -e " ${RED}Offline${NC}: ${CONTAINER} "
  fi
done
if [[ $ZIGBEE2MQTT_START = "NO" ]]; then
  echo -e " ${RED}Offline${NC}: ZigBee container inactive (edit .env to activate)"
fi
echo

# CHECK IF GIT SUBMODULES ARE INSTALLED

external="$EXTERNAL_DRIVE"
mountpoint="$EXTERNAL_MOUNT"

if [ -e "$REMOTE_DIR/app/modules/jc-app" ] && [ -e "$REMOTE_DIR/app/framework/app-fw" ]; then
  :
else
  echo
  echo "Required submodules not installed yet."
  echo "Do you want to do this now [y|n]?"
  while : ; do
    read -n 1 k <& 1
    if [[ $k = y ]] ; then
      sudo git submodule update --init --recursive
      break
    elif [[ $k = n ]] ; then
      echo
      exit 0
    else
      echo
      echo " -> Press 'y' to create a file or 'n' to exit now: "
    fi
  done
fi

# CHECK IF DOCKER-COMPOSE EXISTS

if test -f "$DOCKERCOMPOSE_DIR/docker-compose"; then
  :
else
  echo
  echo "Check the location of your docker-compose file in the configuration!"
  echo "The file/path '$DOCKERCOMPOSE_DIR/docker-compose' doesn't exist. "
  echo
  exit 0
fi

# START MENU WITH AVAILABLE START OPTIONS

if [ ! $config ]; then
  echo
  echo "Start menu (press key):"
  echo $LINE
  echo " 's' - start"
  echo " 'r' - restart"
  echo " 'l' - logfile"
  echo " 'x' - stop"
  echo $LINE
  #echo " 'i' - install sample configuration"
  echo " 'i' - start with messages (not as daemon)"
  echo " 'u' - update from github (branch:$branch)"
  echo " 'v' - update from github (branch:$branch) and rebuild container"
  echo " 'c' - clean docker (stopped container / dangling images)"
  echo " 'd' - clean docker (system incl. build cache)"
  echo $LINE
  echo " 'q' - quit"
  count=0
  while : ; do
    read -n 1 k <&1
    if [[ $k = q ]] ; then
       printf "\n... quitting start script.\n"
       exit 0
    elif [[ $k = s ]] ; then
       config="start"
       printf "\n... starting (via docker-compose up -d).\n"
       break
    elif [[ $k = r ]] ; then
       config="restart"
       printf "\n... restarting.\n"
       break
    elif [[ $k = x ]] ; then
       config="stop"
       printf "\n... stopping.\n"
       break
    elif [[ $k = u ]] ; then
       config="update"
       printf "\n... update from Github.\n"
       break
    elif [[ $k = u ]] ; then
       config="install"
       printf "\n... install sample configuration.\n"
       break
    elif [[ $k = i ]] ; then
       config="start_visible"
       printf "\n... starting (via docker-compose up -d).\n"
       break
    elif [[ $k = v ]] ; then
       config="rebuild"
       printf "\n... update from Github and rebuild docker container.\n"
       break
    elif [[ $k = c ]] ; then
       config="prune"
       printf "\n... cleanup docker containers and images.\n"
       break
    elif [[ $k = d ]] ; then
       config="prune2"
       printf "\n... cleanup docker system.\n"
       break
    elif [[ $k = l ]] ; then
       config="watchlog"
       printf "\n... watch logfile.\n"
       break
    else
       ((count=$count+1))
       printf "\nIterate for $count times\n"
       echo "Press 'q' to exit"
    fi
  done
fi

echo ""

if [ $config == "start" ]; then
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml up -d

    if [ $ZIGBEE2MQTT_START = "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml up -d
    fi

elif [ $config == "start_visible" ]; then
    if [ $ZIGBEE2MQTT_START = "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml up -d
    fi

    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml up

elif [ $config == "restart" ]; then
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml restart

    if [ $ZIGBEE2MQTT_START = "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml restart
    fi

elif [ $config == "install" ]; then
    cd data/_sample
    ./install-config
    cd ../..

elif [ $config = "stop" ]; then

    echo "Stop docker container:"
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml stop

    if [ $ZIGBEE2MQTT_START == "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml stop
    fi

elif [ $config == "update" ]; then

    echo "Change dir"
    cd $REMOTE_DIR

    echo "Stop docker"
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml stop

    if [ $ZIGBEE2MQTT_START == "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml stop
    fi

    echo "Update REMOTE from repository"
    git stash
    git pull

    echo "Update MODULES from repository"
    git submodule update --init --recursive

    echo "Restart docker"
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml up -d

    if [ $ZIGBEE2MQTT_START == "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml up -d
    fi

elif [ $config == "rebuild" ]; then

    echo "Change dir"
    cd $REMOTE_DIR

    echo "Stop docker"
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml stop

    if [ $ZIGBEE2MQTT_START == "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml stop
    fi

    echo "Update REMOTE from repository"
    git stash
    git pull

    echo "Update MODULES from repository"
    git submodule update --init --recursive

    echo "Rebuild docker container"
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml up --build

    if [ $ZIGBEE2MQTT_START == "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml up --build
    fi

    echo "Restart docker"
    $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose.yml up -d

    if [ $ZIGBEE2MQTT_START == "YES" ]; then
      $DOCKERCOMPOSE_DIR/docker-compose -f $REMOTE_DIR/docker-compose-zigbee.yml up -d
    fi

elif [ $config == "prune" ]; then

   docker image prune
   docker container prune

elif [ $config == "prune2" ]; then

   docker system prune

elif [ $config == "watchlog" ]; then

   ./watch_log

else
    echo "not found."
fi

echo
echo "Done."

