#!/bin/bash
#--------------------------

source config_test

rm -rf ../docker-compose.yml
envsubst < "temp.docker-compose.yml" > "../docker-compose.yml"

rm -rf ../app/config_stage.js
envsubst < "temp.rm_stage.js" > "../app/rm_config_stage.js"

rm -rf ../server/modules/config_stage.py
envsubst < "temp.rm3stage.py" > "../server/modules/rm3stage.py"
