#----------------------------------------
# Docker Remote RM
#----------------------------------------
# ${THIS_IS_THE_PROJECT_TEMPLATE}
#----------------------------------------

#services:

  ${REMOTE_DOCKER_SERVER}:
    build: ./config/container
    container_name: ${REMOTE_DOCKER_SERVER}
    volumes:
      - ${REMOTE_DIR_SERVER}:/usr/src/app/server
      - ${REMOTE_DIR_DATA}:${REMOTE_DIR_DATA}
      - ${REMOTE_DIR_ICON_INDEX}:${REMOTE_DIR_ICON_INDEX}
    ports:
      - ${REMOTE_SERVER_PORT}:${REMOTE_SERVER_PORT}



  ${REMOTE_DOCKER_CLIENT}:
    image: ${REMOTE_DOCKERIMAGE_CLIENT}
    container_name: ${REMOTE_DOCKER_CLIENT}
    ports:
      - ${REMOTE_CLIENT_PORT}:5000
    volumes:
      - ${REMOTE_DIR_CLIENT}:/var/www/html/rm3
      - ${REMOTE_DIR_JCMODULES}:/var/www/html/rm3/modules
      - ${REMOTE_DIR_ICONS}:/var/www/html/rm3/icon
      - ./config/apache2/www-rm3.conf:/etc/apache2/sites-enabled/www-rm3.conf
    depends_on:
      - ${REMOTE_DOCKER_SERVER}


#----------------------------------------
